name: test

on:
  release:
    types: [published, edited]
    branches: [main]

jobs:
  test-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Notarize release assets
        uses: codenotary/notarize-release-assets-action@v1.0.0
        # uses: codenotary/notarize-release-assets-action@main
        with:
          cnil_rest_api_url: ${{ secrets.CNIL_REST_API_URL }}
          cnil_personal_token: ${{ secrets.CNIL_PERSONAL_TOKEN }}
          cnil_grpc_host: ${{ secrets.CNIL_GRPC_HOST }}
          cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
          cnil_ledger: ${{ secrets.CNIL_LEDGER_ID }}
          release_url: ${{ github.event.release.url }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
